api_platform:
    title: Desafio Back-end - Payment PHP
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        include_type: true
    # Good defaults for REST APIs
    defaults:
        route_prefix: '/rest'
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        json: ['application/json']
    error_formats:
        json: ['application/json']
    patch_formats:
        json: ['application/json']
